# Generated by Django 5.1.4 on 2024-12-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='The name of the task.', max_length=255)),
                ('priority', models.CharField(choices=[('P2', 'P2'), ('P1', 'P1'), ('P0', 'P0')], default='P1', help_text='The priority level of the task.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('effort_estimation', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated effort in hours', max_digits=5, null=True)),
                ('planned_start_time', models.DateTimeField(blank=True, null=True)),
                ('planned_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('tech_team', 'Tech Team')], default=None, max_length=100, null=True)),
                ('position', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('ui_ux', 'UI/UX Designer'), ('test', 'Tester')], default='frontend', help_text='The role of the team member.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(through='tasks.Assignment', to='tasks.teammember'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.teammember'),
        ),
    ]
