# Generated by Django 5.1.4 on 2024-12-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('ui_ux', 'UI/UX Designer'), ('test', 'Tester'), ('pm', 'Project manager or Production manager')], default='frontend', help_text='The role of the team member.', max_length=20),
        ),
    ]
