# Generated by Django 5.1.4 on 2024-12-22 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('ui_ux', 'UI/UX Designer'), ('test', 'Tester')], default='frontend', help_text='The role of the team member.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.teammember')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(through='tasks.Assignment', to='tasks.teammember'),
        ),
    ]
