# Generated by Django 5.1.4 on 2024-12-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_teammember_assignment_task_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='effort_estimation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated effort in hours', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='planned_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='planned_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
