# Generated by Django 5.1.4 on 2024-12-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_assignment_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, choices=[('tech_team', 'Tech Team')], default=None, max_length=100, null=True),
        ),
    ]
