# Generated by Django 5.1.4 on 2024-12-28 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_historicalassignment_historicaltask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('leave', 'Leave (Not Working)'), ('overtime', 'Overtime (Working)')], max_length=20)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='tasks.teammember')),
            ],
            options={
                'unique_together': {('team_member', 'date')},
            },
        ),
    ]
