# Generated by Django 5.1.4 on 2024-12-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_historicaltask_description_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='real_priority',
            field=models.IntegerField(default=0, help_text='The priority level of the task within its level.'),
        ),
        migrations.AddField(
            model_name='task',
            name='real_priority',
            field=models.IntegerField(default=0, help_text='The priority level of the task within its level.'),
        ),
    ]
