# Generated by Django 5.1.4 on 2024-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_historicaltask_real_priority_task_real_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='level',
            field=models.IntegerField(default=1, help_text='The level of the task in the hierarchy.'),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=1, help_text='The level of the task in the hierarchy.'),
        ),
    ]
