# Generated by Django 5.1.4 on 2024-12-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20241228_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='parent_task',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent task this task belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='The parent task this task belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='tasks.task'),
        ),
    ]
