# Generated by Django 5.1.4 on 2024-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_historicaltask_parent_task_task_parent_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['level', '-priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='workload',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The estimated workload of the task in person-days (only for leaf tasks).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='workload',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The estimated workload of the task in person-days (only for leaf tasks).', max_digits=5, null=True),
        ),
    ]
