# Generated by Django 5.1.4 on 2024-12-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_holiday_workcalendar_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='workload',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workload',
        ),
    ]
