# Generated by Django 5.1.4 on 2024-12-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_options_alter_assignment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['level', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
