# Generated by Django 5.1.4 on 2024-12-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_options_remove_historicaltask_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltask',
            old_name='real_priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='real_priority',
            new_name='priority',
        ),
    ]
