# Generated by Django 5.1.4 on 2025-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_assignment_need_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeriiiDefects',
            fields=[
                ('issue_description', models.TextField(primary_key=True, serialize=False)),
                ('owner', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('sys_name', models.TextField(blank=True, null=True)),
                ('module_name', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('priority_no', models.IntegerField(blank=True, null=True)),
                ('workflow_status', models.TextField(blank=True, null=True)),
                ('creation_time', models.DateField(blank=True, null=True)),
                ('days_since_creation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veriii_defects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeriiiTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('planed_start_time', models.DateField(blank=True, null=True)),
                ('planed_end_time', models.DateField(blank=True, null=True)),
                ('planned_verification_time', models.DateField(blank=True, null=True)),
                ('effort_estimation_in_man_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_start_time', models.DateField(blank=True, null=True)),
                ('actual_end_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veriii_tasks',
                'managed': False,
            },
        ),
    ]
