# Generated by Django 5.1.4 on 2025-01-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_veriiidefects_veriiitasks'),
    ]

    operations = [
        migrations.RunSQL('''
        ALTER TABLE all_veriii_defects ADD COLUMN id SERIAL;
        ''')
    ]
