# Generated by Django 5.1.4 on 2025-01-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20250124_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCompletionWork',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('task_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('owner', models.TextField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('completion_month', models.CharField(blank=True, null=True)),
                ('days_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'all_completion_work',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='veriiitaskassignments',
            table=('veriii_task_assignments',),
        ),
    ]
